name: Check Webpage Changes

on:
  schedule: # Runs every day at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch: # Runs manually from the Actions tab

jobs:
  check-webpage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}  # Use the PAT for checkout

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Use the Python version compatible with your script

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 markdownify gitpython

    - name: Configure Git
      run: |
        git config --global user.name 'raunov'
        git config --global user.email 'rauno@rubio.ee'
      
    - name: Run check-change script
      run: python ./check-change.py
